"use client";

import Link from "next/link";
import { useEffect } from "react";
import { IconArrowLeft, IconSparkles } from "@/components/Icons";

export default function ExerciseError({ error, reset }: { error: Error & { digest?: string }; reset: () => void }) {
  useEffect(() => {
    console.error("Exercise render error:", error);
  }, [error]);

  return (
    <main className="container">
      <div className="card" style={{ textAlign: "center", padding: "3rem 2rem" }}>
        <div className="empty-state-icon" style={{ margin: "0 auto 1rem" }}>
          <IconSparkles className="w-6 h-6" />
        </div>
        <h2 className="title" style={{ fontSize: "1.5rem" }}>
          This exercise couldn&apos;t be displayed
        </h2>
        <p className="muted" style={{ maxWidth: "480px", margin: "0 auto 1.5rem" }}>
          Its data doesn&apos;t match what the app expects to render — this usually happens with an exercise
          generated by an older version of the assistant. Ask for a fresh one instead of retrying this one.
        </p>
        <div style={{ display: "flex", gap: "0.75rem", justifyContent: "center", flexWrap: "wrap" }}>
          <button type="button" onClick={reset} className="btn btn-secondary">
            Try again
          </button>
          <Link href="/">
            <button type="button" className="btn">
              <IconArrowLeft className="w-4 h-4" />
              <span>Back to Home</span>
            </button>
          </Link>
        </div>
      </div>
    </main>
  );
}
